import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
// Generated by `npm run predev`/`prebuild` (cp from ../../design/tokens.css)
// — not committed, so the canonical source stays design/tokens.css. See
// ADR-0008.
import "./tokens.css";
import "./styles.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
